### ISSUE TITLE
1kgenomes beta site

### ISSUE THREAD

**Issue by david4096** [BD2KGenomics/ga4gh-integration#70]
We could do more to automate the deploy, but I set up Apache to run a "beta" area so that we can host more protocol versions from the same box.

I noticed that someone is developing a client that uses the path from the protobuf, which we should do as well. 

The idea is that we could run a few protocol versions off the path like this:
~~http://1kgenomes.ga4gh.org:8000/0.6.0a8/~~ http://1kgenomes.ga4gh.org:8000/v0.6.0a8/

And keep the main 1kgenomes.ga4gh.org at the latest protocol.

@kozbo 

This should make client development easier @Welliton309

**Comment by wdesouza** [comment]
@david4096 it will be great for developing clients for GA4GH API.

It would be useful if there is an endpoint to get information about the server, mainly the protocol version. Clients could verify if they support the protocol version before performing the requests.

**Comment by david4096** [comment]
@Welliton309 the next release has an endpoint `info` that will inform of the protocol version!

https://github.com/ga4gh/ga4gh-server/blob/83a941707668f4fe07a8a21db80ed6437caf99b9/ga4gh/server/backend.py#L693

**Comment by david4096** [comment]
[1kgenomes.ga4gh.org:8000/v0.6.0a8/](http://1kgenomes.ga4gh.org:8000/v0.6.0a8/) is up though it shares resources with the main site. Please let me know your experience!

**Comment by jpdna** [comment]
Could you point me to what branch/commit of ga4gh-server should work with
http://1kgenomes.ga4gh.org:8000/v0.6.0a8/

I am getting the error below when trying to use the python client in REPL which seems like a version mismatch issue:
```
>>> from ga4gh.client import client
>>> c = client.HttpClient("http://1kgenomes.ga4gh.org")
>>> dataset = c.search_datasets().next()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paschallj/GA4GH/server/v1/venv/local/lib/python2.7/site-packages/ga4gh/client/client.py", line 89, in _run_search_request
    protocol_request, object_name, protocol_response_class)
  File "/home/paschallj/GA4GH/server/v1/venv/local/lib/python2.7/site-packages/ga4gh/client/client.py", line 939, in _run_search_page_request
    response.text, protocol_response_class)
  File "/home/paschallj/GA4GH/server/v1/venv/local/lib/python2.7/site-packages/ga4gh/client/client.py", line 37, in _deserialize_response
    return protocol.fromJson(json_response_string, protocol_response_class)
  File "/home/paschallj/GA4GH/server/v1/venv/local/lib/python2.7/site-packages/ga4gh/schemas/protocol.py", line 154, in fromJson
    return json_format.Parse(json, protoClass())
  File "/home/paschallj/GA4GH/server/v1/venv/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 369, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/home/paschallj/GA4GH/server/v1/venv/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 384, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/home/paschallj/GA4GH/server/v1/venv/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 415, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/home/paschallj/GA4GH/server/v1/venv/local/lib/python2.7/site-packages/google/protobuf/json_format.py", line 501, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse datasets field: Message type "ga4gh.schemas.ga4gh.Dataset" has no field named "info".


```

**Comment by david4096** [comment]
PEBCAK sorry, that is a9, running at the endpoint so the currently released version should work. I will be taking down the (mistakenly named) a8 shortly as we're about to release a10.

http://1kgenomes.ga4gh.org:8000/v0.6.0a9/
